name: Create Release

on:
  push:
    branches:
      - 'releases/latest'

jobs:
  release:
    runs-on: ubuntu-20.04
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3
      - id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ACTION }}

  update-branch-name:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/releases/latest
      - name: Update branch name
        run: |
          git branch -m releases/latest releases/v${{ needs.release.outputs.version }}
          git push origin HEAD:releases/v${{ needs.release.outputs.version }}
          git checkout -b main
          git push origin --delete releases/latest
          git branch releases/latest main
          git push origin HEAD:releases/latest

  